package postgres

import (
	"encoding/json"
	"fmt"
	"strings"

	"gosalusa.com/database/dialects"
	"gosalusa.com/database/dialects/generic"
)

// PosgtgresCore implements generic.Core for PostgreSQL. It quotes identifiers
// with double quotes, uses incrementing $1, $2, ... bindings, and supports
// RETURNING.
type PosgtgresCore struct {
	bindingNumber int
}

// Identifier returns s quoted as a PostgreSQL identifier. A "*" segment is
// left unquoted.
func (*PosgtgresCore) Identifier(s string) string {
	if s == "*" {
		return s
	}
	parts := strings.Split(s, ".")
	for i, p := range parts {
		if p == "*" {
			continue
		}
		parts[i] = "\"" + p + "\""
	}
	return strings.Join(parts, ".")
}

// DataType maps a dialects.DataType to a PostgreSQL column type.
func (*PosgtgresCore) DataType(t dialects.DataType) string {
	switch t.Name {
	case dialects.DataTypeBlob.Name:
		return "BYTEA"
	case dialects.DataTypeString.Name:
		return "TEXT"
	case dialects.DataTypeEnum.Name:
		panic("not implemented")

	case dialects.DataTypeBoolean.Name:
		return "BOOLEAN"

	case dialects.DataTypeDate.Name, dialects.DataTypeDateTime.Name:
		return "TIMESTAMP"

	case dialects.DataTypeFloat32.Name:
		return "REAL"
	case dialects.DataTypeFloat64.Name:
		return "DOUBLE PRECISION"

	case dialects.DataTypeInt8.Name, dialects.DataTypeInt16.Name, dialects.DataTypeUInt8.Name, dialects.DataTypeUInt16.Name:
		return "SMALLINT"
	case dialects.DataTypeInt32.Name, dialects.DataTypeUInt32.Name:
		return "INTEGER"
	case dialects.DataTypeInt64.Name, dialects.DataTypeUInt64.Name:
		return "BIGINT"

	case dialects.DataTypeJSON.Name:
		return "JSONB"
	}
	return string(t.Name)
}

// CurrentTime returns the PostgreSQL expression for the current timestamp.
func (*PosgtgresCore) CurrentTime() string {
	return "CURRENT_TIMESTAMP()"
}

// AutoIncrement returns the clause that makes a column an auto-incrementing
// primary key in PostgreSQL.
func (*PosgtgresCore) AutoIncrement() string {
	return "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
}

// Escape renders v as a SQL literal, doubling embedded single quotes in
// strings, rendering booleans as TRUE or FALSE, and JSON-marshaling unknown
// types.
func (s *PosgtgresCore) Escape(v any) string {
	switch v := v.(type) {
	case string:
		return "'" + strings.ReplaceAll(v, "'", "''") + "'"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64,
		float32, float64:
		return fmt.Sprint(v)
	case bool:
		if v {
			return "TRUE"
		} else {
			return "FALSE"
		}
	default:
		b, err := json.Marshal(v)
		if err != nil {
			panic(fmt.Errorf("failed to escape value: %w", err))
		}
		return s.Escape(string(b))
	}
}

// Binding returns the next PostgreSQL binding placeholder in the sequence
// ($1, $2, ...).
func (p *PosgtgresCore) Binding() string {
	p.bindingNumber++
	return fmt.Sprintf("$%d", p.bindingNumber)
}

// Features reports the capabilities supported by PostgreSQL, which include
// RETURNING.
func (s *PosgtgresCore) Features() dialects.Features {
	return dialects.Features{
		Returning: true,
	}
}

// New returns a dialect that renders SQL for PostgreSQL.
func New() dialects.Dialect {
	return generic.New(&PosgtgresCore{})
}

// UsePostgres registers the PostgreSQL dialect under the "postgres" driver
// name.
func UsePostgres() {
	dialects.Register("postgres", New)
}
func init() {
	UsePostgres()
}
