package generic_test

import (
	"testing"

	"gosalusa.com/database/dialects"
	"gosalusa.com/database/dialects/generic"
	"gosalusa.com/database/dialects/postgres"
	"gosalusa.com/internal/test"
)

func TestGeneric_EncodeCreateTableQuery(t *testing.T) {
	g := generic.New(&testCore{})
	test.EncoderTest(t, g.EncodeCreateTableQuery, []test.EncoderTestCase[*dialects.CreateTableQuery]{
		{
			Name: "simple",
			Builder: &dialects.CreateTableQuery{
				Table: "foo",
				Columns: []dialects.ColumnDefinition{
					{Name: "c1", Datatype: dialects.DataTypeDate},
				},
			},
			ExpectedSQL:      "CREATE TABLE `foo` (`c1` date NOT NULL);",
			ExpectedBindings: []any{},
		},
		{
			Name: "multi",
			Builder: &dialects.CreateTableQuery{
				Table: "foo",
				Columns: []dialects.ColumnDefinition{
					{Name: "c1", Datatype: dialects.DataTypeDate},
					{Name: "c2", Datatype: dialects.DataTypeInt64},
				},
			},
			ExpectedSQL:      "CREATE TABLE `foo` (`c1` date NOT NULL, `c2` int64 NOT NULL);",
			ExpectedBindings: []any{},
		},
		{
			Name: "temp",
			Builder: &dialects.CreateTableQuery{
				Table:     "foo",
				Temporary: true,
				Columns: []dialects.ColumnDefinition{
					{Name: "c1", Datatype: dialects.DataTypeDate},
				},
			},
			ExpectedSQL:      "CREATE TEMPORARY TABLE `foo` (`c1` date NOT NULL);",
			ExpectedBindings: []any{},
		},
		{
			Name: "full",
			Builder: &dialects.CreateTableQuery{
				Table: "foo",
				Columns: []dialects.ColumnDefinition{
					{Name: "id", Datatype: dialects.DataTypeInt32, Primary: true},
					{Name: "name", Datatype: dialects.DataTypeString, Unique: true},
					{Name: "optional", Datatype: dialects.DataTypeString, Nullable: true},
				},
			},
			ExpectedSQL:      "CREATE TABLE `foo` (`id` int32 PRIMARY KEY NOT NULL, `name` string NOT NULL UNIQUE, `optional` string);",
			ExpectedBindings: []any{},
		},
	})
}

func TestGeneric_EncodeCreateTableQueryPostgres(t *testing.T) {
	g := postgres.New()
	test.EncoderTest(t, g.EncodeCreateTableQuery, []test.EncoderTestCase[*dialects.CreateTableQuery]{
		{
			Name: "full",
			Builder: &dialects.CreateTableQuery{
				Table: "foo",
				Columns: []dialects.ColumnDefinition{
					{Name: "id", Datatype: dialects.DataTypeInt32, AutoIncrement: true},
				},
			},
			ExpectedSQL:      `CREATE TABLE "foo" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL);`,
			ExpectedBindings: []any{},
		},
	})
}
